#!/usr/bin/env bash
set -euo pipefail

INSTALL_USER="${SUDO_USER:-$USER}"
INSTALL_HOME="$(getent passwd "$INSTALL_USER" | cut -d: -f6)"
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="$INSTALL_HOME/.config/KlipperDWIN"
ENV_FILE="$CONFIG_DIR/KlipperDWIN.env"

read_value() {
    local key="$1"
    local default="$2"
    local value=""
    if [[ -f "$ENV_FILE" ]]; then
        value="$(sed -n "s/^${key}=//p" "$ENV_FILE" | tail -n 1)"
        value="${value%\"}"
        value="${value#\"}"
    fi
    printf '%s' "${value:-$default}"
}

prompt_value() {
    local label="$1"
    local current="$2"
    local result=""
    read -r -p "$label [$current]: " result
    printf '%s' "${result:-$current}"
}

mkdir -p "$CONFIG_DIR"

moonraker_url="$(prompt_value "Moonraker URL" "$(read_value MOONRAKER_URL http://127.0.0.1:7125)")"
serial_port="$(prompt_value "Serial port" "$(read_value DWIN_SERIAL_PORT /dev/ttyS0)")"
encoder_a="$(read_value DWIN_ENCODER_PINS "21 19")"
encoder_a="${encoder_a%% *}"
encoder_b_raw="$(read_value DWIN_ENCODER_PINS "21 19")"
encoder_b="${encoder_b_raw#* }"
encoder_a="$(prompt_value "Encoder A GPIO (BCM)" "$encoder_a")"
encoder_b="$(prompt_value "Encoder B GPIO (BCM)" "$encoder_b")"
button_pin="$(prompt_value "Encoder button GPIO (BCM)" "$(read_value DWIN_BUTTON_PIN 20)")"
power_device="$(prompt_value "Moonraker power device" "$(read_value DWIN_POWER_DEVICE Printer)")"
power_on_hold_ms="$(prompt_value "Power-on button hold time (ms, 0 = immediate)" "$(read_value DWIN_POWER_ON_HOLD_MS 2000)")"
if ! [[ "$power_on_hold_ms" =~ ^[0-9]+$ ]]; then
    echo "Power-on button hold time must be zero or a positive integer." >&2
    exit 1
fi
request_timeout="$(read_value DWIN_REQUEST_TIMEOUT 5)"
api_key="$(read_value MOONRAKER_API_KEY "")"
settings_file="$CONFIG_DIR/presets.json"

cat > "$ENV_FILE" <<EOF
# KlipperDWIN runtime configuration.
# Generated by configure.sh. Values use systemd EnvironmentFile syntax.
MOONRAKER_URL=$moonraker_url
MOONRAKER_API_KEY=$api_key
DWIN_REQUEST_TIMEOUT=$request_timeout
DWIN_SERIAL_PORT=$serial_port
DWIN_ENCODER_PINS="$encoder_a $encoder_b"
DWIN_BUTTON_PIN=$button_pin
DWIN_SETTINGS_FILE=$settings_file
DWIN_POWER_DEVICE=$power_device
DWIN_POWER_ON_HOLD_MS=$power_on_hold_ms
EOF

chown "$INSTALL_USER:$INSTALL_USER" "$ENV_FILE"
chmod 600 "$ENV_FILE"

echo
echo "Configuration saved to $ENV_FILE"

if systemctl list-unit-files KlipperDWIN.service >/dev/null 2>&1; then
    answer=""
    read -r -p "Restart KlipperDWIN now? [Y/n]: " answer
    case "${answer:-Y}" in
        [Yy]*)
            sudo systemctl restart KlipperDWIN.service
            echo "KlipperDWIN.service restarted."
            ;;
    esac
fi
